spring:
  application:
    name: api-gateway
    
    
server:
  port: 1101
  
  
eureka: 
  client:
    service-url: 
      defaultZone: http://localhost:1001/eureka/
#  instance:
#    ip-address: true  
   
zuul:
  routes:
    eureka-client: 
      path: /eureka-client/**
      service-id: eureka-client
  
#zuul:
#  routes:
#    eureka-client: 
#      path: /eureka-client/**
#      service-id: eureka-client
   
      
      
  
  