spring:
  application:
    name: config-client
  cloud:
    config:
      retry: #和重试机制相关的配置有如下四个：
        max-attempts: 6   # 配置重试次数，默认为6
        multiplier: 1.1   # 间隔乘数，默认1.1
        initial-interval: 1000  # 初始重试间隔时间，默认1000ms
        max-interval: 2000  # 最大间隔时间，默认2000ms
    
server:
  port: 4002
        
logging:
  level:
    root: info
    
management:
  endpoints:
    web:
      exposure:
        include:
        - refresh
        - health
        - info
