spring:
  application:
    name: eureka-client
    
server: 
  port: 2001
  
eureka: 
  client:
    service-url: 
      defaultZone: http://localhost:1001/eureka/
#  instance:
#    ip-address: true

logging:
  level:
    root: info

#management.security.enabled=false
#management:
#  security: 
#    enabled: false
      