spring:
  application:
    name: eureka-client
    
server:
  port: 2001

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/
  instance:
    prefer-ip-address: true
  
management:
  endpoints:
    web:
      exposure:
        include:
        - refresh
        - health
        - info
        
logging:
  level:
    root: info