server:
  port: 2007
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/
 
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    
spring:
  sleuth:
    sampler:
      rate: 1  
      
  rabbitmq:
    host: localhost
    port: 5672
    username: spring
    password: 123456
  zipkin:
    sender:
      type: rabbit
    
zipkin:
  rabbitmq: 
    queue: hello
      
