spring:
  application:
    name: trace-4
  sleuth:
    sampler:
      rate: 1    # 则每次的信息都进入了zipkin
  rabbitmq:
    host: localhost
    port: 5672
    username: spring
    password: 123456
  zipkin:
    sender:
      type: rabbit
      
zipkin:
  rabbitmq:
    queue: hello

server:
  port: 2008
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/
 
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG
   
   
   