spring:
  application:
    name: trace-2
  zipkin:
    base-url: http://localhost:9411   #配置zipkin-server的地址
  sleuth:
    sampler:
      rate: 1    # 则每次的信息都进入了zipkin

server:
  port: 2006
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1001/eureka/
 
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    
