spring:
  application:
    name: api-gateway
    
server:
  port: 3001
  
eureka: 
  client:
    service-url: 
      defaultZone: http://localhost:1001/eureka/
  instance:
   prefer-ip-address: true
   
zuul:
  routes:
    eureka-client: 
      path: /eureka-client/**
      service-id: eureka-client
    eureka-consumer: 
      path: /eureka-consumer/**
      service-id: eureka-consumer
       