spring:
  application:
    name: api-gateway
    
server:
  port: 3001
  
eureka: 
  client:
    service-url: 
      defaultZone: http://localhost:1001/eureka/
  instance:
   prefer-ip-address: true
   
zuul:
  routes:
    client-eureka: 
      path: /client-eureka/**
      service-id: client-eureka
    consumer-eureka: 
      path: /consumer-eureka/**
      service-id: consumer-eureka
       